<?php
	
	//Checks whether the user is logged in or not...
	session_start();
	if($_SESSION['id'] == ''){
		header('Location: '.$_SESSION['login'].'?flag=3');
		exit();
	}
	//Login Check ends...

	//Adding Connection String
	if(!file_exists($_SESSION['path'].$_SESSION['connection'])){
		header('Location: '.$_SESSION['login'].'?flag=6');
		exit();
	}
	require($_SESSION['path'].$_SESSION['connection']);
	//Adding Connection String ends
	
	//Checks whether the required values are null or not(server-side checking)...
	if(!isset($_POST['request_type']) || !isset($_POST['user_name']) || !isset($_POST['email']) || !isset($_POST['type'])){
		header('Location: ' . $_SESSION['home'] . '?flag=20');
		exit();
	}
	//null check ends...

	//receives inputs from the "File_Adder_Admin.php" page...
	$request_type = htmlspecialchars($_POST['request_type']);
	$user_name = htmlspecialchars($_POST['user_name']);
	$email = htmlspecialchars($_POST['email']);
	$type = htmlspecialchars($_POST['type']);
	//end of input...

	$type_detail = ($type=='A')?'Administrator':'User';
	$qry = 'default';
	$default = 'welcome@123';
	$body = 'Your account in NIBMG web portal has been updated...';
	$subject = '';

	//Setting up the flag...
	$flag_value = '';
	if($request_type == 'insert'){
		$flag_value =	10;
	}
	elseif($request_type == 'edit'){
		$flag_value =	11;
	}
	elseif($request_type == 'delete'){
		$flag_value =	12;
	}
	elseif($request_type == 'reset'){
		$flag_value =	13;
	}
	elseif($request_type == 'reactivate'){
		$flag_value =	14;
	}
	//Flag setting ends...

	//insertion into the users table...
	if($request_type == 'insert'){
		$qry = "select stat from users where email = '$email'";
		$result = mysqli_fetch_array(mysqli_query($cn, $qry));
		if($result){	//redirects to Home page if the inserted user data is already in database...
			if($result['stat'] == 0){
				header('Location: '.$_SESSION['home'].'?flag=6');
				mysqli_close($cn);
				exit();
			}
			else{
				mysqli_close($cn);
				header('Location: '.$_SESSION['home'].'?flag=7');
				exit();
			}
		}
		//inserts the user into the database...
		else{
			$qry = "insert into users(user_name,email,stat,type) values('$user_name','$email',1,'$type')";
			
			$subject = 'Welcome Message from NIBMG web portal';
			$body = "Hi $user_name,\n	Welcome to NIBMG webportal. You have successfully completed the registration procedure. You can access your account by using the following credentials::
					\nid::		      $email\nPassword::	$default\naccount type::	".	$type_detail . "
					\nYou are requested to change your password immidiately after the first login. Please do not share your credentials with anyone unless you are approached with proper documentation and proof of identity. In case of any discrepancies, please contact the administrator.\n(*This is an autogenerated email, please do not reply.)
					\nRegards,\n-NIBMG web team.";
		}
	}
	//insertion ends...
	
	//Editing the existing users...
	else if($request_type == 'edit'){
		if(!isset($_POST['old_id'])){
			header('Location: '.$_SESSION['home'].'?flag=1');
			exit();
		}

		$old_id = htmlspecialchars($_POST['old_id']);
		$qry = "update users set user_name = '$user_name', email = '$email', type = '$type' where email = '$old_id'";
		
		$subject = 'Updation of account information in NIBMG web portal';
		$body = "Hi $user_name,\n	Your account information has been changed by ".$_SESSION['name']." (".$_SESSION['id']."). You can access your account by using the following credentials::
				\nName::		  $user_name\nid::		      $email\naccount type::	".	$type_detail . "
				\nIn case of any discrepancies, please contact the administrator.\n(*This is an autogenerated email, please do not reply.)
				\nRegards,\n-NIBMG web team.";
	}
	//Editing ends...

	//Deletion of users...
	else if($request_type == 'delete'){
		$qry = "update users set stat = 0 where email = '$email'";
		
		$subject = 'Deletion of account in NIBMG web portal';
		$body = "Hi $user_name,\n	Your account has been deactivated by our administrator.\n(*This is an autogenerated email, please do not reply.)
				\nRegards,\n-NIBMG web team.";
	}
	//Deletion ends...

	//Resetting the password...	
	else if($request_type == 'reset'){
		$qry = "update users set pswd = 'welcome@123' where email = '$email'";
		
		$subject = 'Password reset in NIBMG web portal';
		$body = "Hi $user_name,\n	Password to your account has been reset by ".$_SESSION['name']." (".$_SESSION['id'].").
				\nYour new password is::	$default
				\nIn case of any discrepancies, please contact the administrator.\n(*This is an autogenerated email, please do not reply.)
				\nRegards,\n-NIBMG web team.";
	}
	//Resetting ends...

	//Reactivation of the deleted users...
	else if($request_type == 'reactivate'){
		$qry = "update users set stat = 1 where user_name = '$user_name' and email = '$email' and type = '$type'";
		
		$subject = 'Reactivation of account in NIBMG web portal';
		$body = "Hi $user_name,\n	Your account has been reactivated by our administrator. You can access it with your previous credentials.\n(*This is an autogenerated email, please do not reply.)
				\nRegards,\n-NIBMG web team.";
	}
	//Reactivation ends...

	//Default: Redirection to the Home page...
	else{
		header('Location: '.$_SESSION['home'].'?flag=2');
	}
	//End of default...

	//echo $qry;

	

	//Execution of the query...
	if(mysqli_query($cn, $qry)){
		mysqli_close($cn);
		if($request_type != 'edit'){
			$old_id = '';
		}
		send_infomail($request_type, $email, $old_id, $user_name, $subject, $body, $flag_value);
		header('Location: '.$_SESSION['home'].'?flag='.$flag_value);
		exit();
	}
	//Execution ends...

	//Failure will lead to the Home page...
	else{
		mysqli_close($cn);echo($qry);
		header('Location: '.$_SESSION['home'].'?flag=4');
		exit();
	}
	//Failure ends...

	//send_infomail() start
	function send_infomail($request_type, $email, $old_id, $user_name, $subject, $body, $flag_value){
		require_once $_SESSION['path'].'/Data_Portal/Backend/Admin/Mailer.php';
		if($result == 1){
			header('Location: '.$_SESSION['home'].'?flag='.$flag_value);
			exit();
		}
		else{
			header('Location: '.$_SESSION['home'].'?flag='.$flag_value.'+1');
			exit();
		}
	}
	//send_infomail() end

?>